# اگر می‌خواهید از قبل مطمئن شوید فایل .gitattributes حاوی الگوهای LFS نیست، 
# می‌توانید خط زیر را اجرا کنید (اختیاری):
# notepad .gitattributes

# آرایه‌ای از مسیرهایی که می‌خواهید پاک شوند.
# در اینجا باید «مسیر نسبی» (نسبت به ریشه مخزن) نوشته شود.
ForEach ($file in @(
    "website/static/img/gallery/autotx.png",
    "website/static/img/autogen_app.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-66-33.jpg",
    "website/docs/autogen-studio/img/skill.png",
    "website/_blogs/2023-11-13-OAI-assistants/img/teaser.jpg",
    "website/_blogs/2024-12-20-RealtimeAgent/img/6_flight_refunded.png",
    "website/_blogs/2023-11-09-EcoAssistant/img/template-demo.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/twilio_endpoint_config.png",
    "website/docs/tutorial/assets/code-execution-in-conversation.png",
    "website/docs/tutorial/assets/conversable-agent.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-79-56.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-42-11.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-93-4.jpg",
    "website/_blogs/2024-12-20-RealtimeAgent/img/realtime_agent_swarm.png",
    "website/docs/autogen-studio/img/workflow_profile.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-51-16.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-65-30.jpg",
    "website/docs/Use-Cases/images/app.png",
    "website/docs/ecosystem/img/ecosystem-ollama.png",
    "test/test_files/test_image.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-53-19.jpg",
    "notebook/nested_chat_2.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-39-6.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-64-28.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-92-3.jpg",
    "website/static/img/gallery/webagent.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-63-26.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-36-5.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-39-7.jpg",
    "website/_blogs/2025-01-10-WebSockets/img/structured_messages_with_websockets.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/2_incoming_call.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-65-31.jpg",
    "website/_blogs/2023-04-21-LLM-tuning-math/img/level4algebra.png",
    "website/static/img/autogen_agentchat.png",
    "website/docs/tutorial/assets/code-executor-no-docker.png",
    "website/_blogs/2024-03-03-AutoGen-Update/img/contributors.png",
    "website/_blogs/2024-11-27-Prompt-Leakage-Probing/img/prompt_leakage_report.png",
    "website/static/img/gallery/default.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-81-58.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-39-8.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-61-22.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-80-57.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-71-44.jpg",
    "website/_blogs/2023-11-20-AgentEval/img/math-problems-plot.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/1_service_running.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-66-34.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-42-12.jpg",
    "website/docs/tutorial/assets/human-in-the-loop.png",
    "website/_blogs/2024-12-20-Reasoning-Update/img/mcts_example.png",
    "website/docs/autogen-studio/img/agent_new.png",
    "website/_blogs/2024-03-11-AutoDefense/img/table-4agents.png",
    "website/_blogs/2023-10-26-TeachableAgent/img/teachable-arch.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-68-38.jpg",
    "website/_blogs/2023-11-09-EcoAssistant/img/results.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-1-1.jpg",
    "website/_blogs/2024-05-24-Agent/img/agents.png",
    "website/_blogs/2024-07-25-AgentOps/img/flow.png",
    "website/static/img/cover.png",
    "website/_blogs/2025-01-08-RealtimeAgent-over-websocket/img/websocket_communication_diagram.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-40-9.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-62-25.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-68-37.jpg",
    "website/_blogs/2023-12-01-AutoGenStudio/img/autogenstudio_home.png",
    "website/_blogs/2024-07-25-AgentOps/img/session-replay.png",
    "website/static/img/gallery/composio-autogen.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/5_refund_policy.png",
    "notebook/tree_of_thoughts.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-85-61.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-12-2.jpg",
    "website/_blogs/2023-05-18-GPT-adaptive-humaneval/img/design.png",
    "website/docs/autogen-studio/img/workflow_test.png",
    "website/docs/tutorial/assets/code-executor-docker.png",
    "notebook/nested_chat_1.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-43-13.jpg",
    "website/static/img/gallery/x-force-ide-ui.png",
    "website/_blogs/2023-12-01-AutoGenStudio/img/autogenstudio_config.png",
    "website/_blogs/2024-03-03-AutoGen-Update/img/love.png",
    "notebook/swarm_enhanced_03.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-67-35.jpg",
    "website/static/img/gallery/robot.jpg",
    "website/docs/autogen-studio/img/workflow_sequential.png",
    "website/docs/autogen-studio/img/workflow_new.png",
    "notebook/swarm_enhanced_05.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-52-17.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-94-5.jpg",
    "website/static/img/gallery/TensionCode.png",
    "website/docs/autogen-studio/img/agent_assistant.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-32-3.jpg",
    "website/_blogs/2023-04-21-LLM-tuning-math/img/level3algebra.png",
    "website/docs/ecosystem/img/ecosystem-fabric.png",
    "website/static/img/homepage-hero-background.png",
    "website/docs/ecosystem/img/ecosystem-memgpt.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-75-48.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-73-46.jpg",
    "website/_blogs/2024-03-03-AutoGen-Update/img/gaia.png",
    "notebook/swarm_enhanced_04.png",
    "notebook/viz_gc.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-2-1.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-66-32.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-61-24.jpg",
    "website/static/img/homepage-hero-background-large.png",
    "website/_blogs/2025-01-09-RealtimeAgent-over-WebRTC/img/webrtc_communication_diagram.png",
    "website/docs/tutorial/assets/sequential-two-agent-chat.png",
    "website/_blogs/2024-03-11-AutoDefense/img/table-compared-methods.png",
    "website/_blogs/2024-12-20-Reasoning-Update/img/reasoningagent_1.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/4_flight_number_name.png",
    "website/docs/ecosystem/img/ecosystem-composio.png",
    "notebook/agentchat_pdf_rag/processed_elements.json",
    "notebook/neo4j_property_graph_1.png",
    "website/_blogs/2023-06-28-MathChat/img/mathchatflow.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-33-2.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-70-43.jpg",
    "notebook/swarm_enhanced_02.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-70-41.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-52-18.jpg",
    "website/docs/Use-Cases/images/autogen_agents.png",
    "website/_blogs/2025-01-09-RealtimeAgent-over-WebRTC/img/webrtc_connection_diagram.png",
    "website/docs/tutorial/assets/two-agent-chat.png",
    "website/_blogs/2023-10-18-RetrieveChat/img/retrievechat-arch.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-63-27.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-69-39.jpg",
    "website/_blogs/2023-05-18-GPT-adaptive-humaneval/img/humaneval.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-75-49.jpg",
    "website/static/img/create_gcp_svc.png",
    "website/docs/autogen-studio/img/model_new.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-75-50.jpg",
    "website/_blogs/2023-04-21-LLM-tuning-math/img/level2algebra.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-73-47.jpg",
    "website/_blogs/2024-03-03-AutoGen-Update/img/dalle_gpt4v.png",
    "website/docs/autogen-studio/img/ara_stockprices.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-54-20.jpg",
    "notebook/neo4j_property_graph_2.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-41-10.jpg",
    "website/_blogs/2024-06-24-AltModels-Classes/img/agentstogether.jpeg",
    "website/docs/autogen-studio/img/workflow_export.png",
    "website/_blogs/2024-01-25-AutoGenBench/img/teaser.jpg",
    "website/_blogs/2024-05-24-Agent/img/leadership.png",
    "website/docs/tutorial/assets/group-chat.png",
    "notebook/friendly_and_suspicous.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-50-15.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-78-53.jpg",
    "website/_blogs/2023-04-21-LLM-tuning-math/img/level5algebra.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-64-29.jpg",
    "website/static/img/os1.png",
    "website/docs/autogen-studio/img/agent_groupchat.png",
    "website/_blogs/2024-02-02-AutoAnny/img/AutoAnnyLogo.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-33-4.jpg",
    "website/_blogs/2023-11-09-EcoAssistant/img/template.png",
    "website/_blogs/2024-03-11-AutoDefense/img/table-agents.png",
    "website/_blogs/2024-07-25-AgentOps/img/autogen-integration.png",
    "website/docs/ecosystem/img/ecosystem-databricks.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/figure-95-6.jpg",
    "website/_blogs/2024-07-25-AgentOps/img/dashboard.png",
    "website/static/img/chat_example.png",
    "notebook/swarm_enhanced_01.png",
    "notebook/nested-chats-chess.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-72-45.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-60-21.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-61-23.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-95-62.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-77-52.jpg",
    "website/_blogs/2024-02-29-StateFlow/img/bash_result.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-82-59.jpg",
    "notebook/optiGuide_new_design.png",
    "notebook/stateflow-swarm-example.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-79-55.jpg",
    "website/docs/autogen-studio/img/agent_skillsmodel.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-79-54.jpg",
    "website/docs/autogen-studio/img/model_openai.png",
    "website/docs/ecosystem/img/ecosystem-promptflow.png",
    "website/_blogs/2024-12-20-RealtimeAgent/img/3_request_for_flight_cancellation.png",
    "website/docs/ecosystem/img/ecosystem-llamaindex.png",
    "notebook/agentchat_pdf_rag/input_files/nvidia_10k_2024.pdf",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-83-60.jpg",
    "website/_blogs/2023-06-28-MathChat/img/result.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-68-36.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-69-40.jpg",
    "website/_blogs/2023-12-01-AutoGenStudio/img/autogenstudio_skills.png",
    "website/_blogs/2024-12-02-ReasoningAgent2/img/tree-of-thoughts.png",
    "website/docs/topics/non-openai-models/images/cloudlocalproxy.png",
    "notebook/agentchat_pdf_rag/parsed_elements.json",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-47-14.jpg",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-76-51.jpg",
    "notebook/neo4j_property_graph_3.png",
    "website/_blogs/2024-12-06-FalkorDB-Structured/img/falkordb.png",
    "website/_blogs/2023-11-06-LMM-Agent/img/teaser.png",
    "notebook/agentchat_pdf_rag/parsed_pdf_info/table-70-42.jpg",
    "website/_blogs/2024-03-03-AutoGen-Update/img/teach.png",
    "website/docs/Use-Cases/images/agent_example.png",
    "website/docs/tutorial/assets/nested-chats.png",
    "website/docs/autogen-studio/img/workflow_chat.png",
    "website/_blogs/2024-02-29-StateFlow/img/alfworld.png"
)) {
    # ابتدا چک می‌کنیم فایل واقعاً وجود دارد یا نه
    if(Test-Path $file) {
        git rm --cached $file      # حذف از ایندکس گیت
        Remove-Item $file          # حذف از دیسک
        Write-Host "Removed $file"
    } else {
        Write-Host "File not found: $file"
    }
}

# پس از حذف فایل‌ها، یک کامیت جدید می‌سازیم
git commit -m "Remove LFS files"

# در نهایت با Force پوش می‌کنیم
git push origin master --force
